name: "Create changelog"
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: Release
        uses: mikepenz/release-changelog-builder-action@v1.4.3
        with:
          outputFile: 'CHANGELOG.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}