name: Keep the versions up-to-date

on:
  push:
    branches:
      - nk/docs

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Actions-R-Us/actions-tagger@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: 'false'