name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Actions-R-Us/actions-tagger@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}