name: Bump Version
on:
  push:
    branches:
      - nk/docs

jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: "Automated Version Bump"
        id: version-bump-action
        uses: "phips28/gh-action-bump-version@v8.0.18"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "cat package.json"
        run: cat ./package.json
      - name:  'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump-action.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Changelog
        uses: scottbrenner/generate-changelog-action@1.0.3
        id: Changelog

      - name: Create Release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}