name: Bump Version
on:
  push:
    branches:
      - master

jobs:
  bump-version:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v1

      - name: "🚀️ Generate release changelog"
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}