name: Bump Version
on:
  push:
    branches:
      - nk/docs
    tags:
      - '*'

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: "📥 Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: "Automated Version Bump"
        id: version-bump-action
        uses: "phips28/gh-action-bump-version@v8.0.18"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "cat package.json"
        run: cat ./package.json
      - name:  'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump-action.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v1

      - name: "🚀️ Generate release changelog"
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"